serokell/xrefcheck

- .crossref-verifier.yaml
- .github/pull_request_template.md
Problem: default config is not really smart and seems easier to just
unlicense it, i. e. let everyone do whatever they want with it.
Also it does not have SPDX header (like any other file in this repo,
but that's another story).
Solution: add SPDX header stating that the Unlicense applies.
Make Serokell copyright holder of it, AFAIK @martoon is fine with
that (and I am not sure whether copyright holder matters for
unlicensed files at all).
That's for a private project.
- Tests
- Haddock
of Public …
> Unlicense default config

- default.nix
- src/Crv/Progress.hs
Haddock failure now make CI report a failure.
None
- Tests
- Haddock
> Fix CI to fail when haddock fails

- .gitignore
- default.nix
- package.yaml
Build binary instead of a library so that the old `nix run -f <crossref-verifier> -c crossref-verifier` approach on CI's works.
None
- Tests
- Haddock
> Build binary by default

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/task.md
Problem: by default, when creating an issue, user has to fill everything
from scratch and this is not good.
Solution: add issue templates for `task` and `bug`, refer people to
page for openning new issue in `CONTRIBUTING.md`.
Addresses [this comment](https://github.com/serokell/crossref-verifier/pull/6#issuecomment-562537893).
- Tests
- Haddock
> Add issue templates

- default.nix
`default.nix` was returning a set with a single derivation instead of a derivation. It works with `nix run` and `nix-build`, because they traverse all values in a set, but doesn't allow to use the package in places where a derivation is expected.
> default.nix: return a derivation instead of a set

- .buildkite/pipeline.yml
- crossref-verifier.nix
- default.nix
- release/default.nix
Change `crossref-verifier.nix` and add `static.nix` so that building a fully static executable is possible.
Results look like this:
[crossref-verify.gz](https://github.com/serokell/crossref-verifier/files/3991431/crossref-verify.gz)
It's probably better if someone checks this on multiple distros before we merge.
https://issues.serokell.io/issue/INT-111
- Tests
- Haddock
> [INT-111] Allow to build crossref-verify statically

- .buildkite/pipeline.yml
We now inject the GITHUB_TOKEN via a vault environment hook, this means there's no longer any need for the niv-bot-token and we should be able to remove it.
> buildkite: inject GITHUB_TOKEN via vault

- .buildkite/pipeline.yml
- nix/sources.json
- nix/sources.nix
- xrefcheck.nix
This PR uses a patched `haskell.nix`, which allows to automatically generate the cache instead of explicitly specifying it in `crossref-verifier.nix` and `sources.json`.
None
- Tests
- Haddock
> Automatically generate haskell.nix cache

- README.md
- nix/sources.json
Updates various stuff in nix.
- Drops `lootbox` from `sources.json`, since the dependency is not auto-generated;
- Updates README.md to reflect the updated `haskell.nix`.
None
- Tests
- Haddock
and
> Various nix changes

- default.nix
- xrefcheck.nix
This removes an extraneous check that haddock finishes correctly. This
is now enforced upstream, so we shouldn't need a secondary check
here. Please, if you have time, make haddock fail and check if it
fails the build now.
None
- Tests
- Haddock
and
> Remove haddock enforcer

- nix/sources.json
- xrefcheck.nix
https://github.com/input-output-hk/haskell.nix/commit/775c8cf756c08a779bbc587013c27f4f4b3df71a fixed a bunch of problems with musl, we can now simplify and only need the custom zlib.
> xrefcheck.nix: bump hs.nix, remove unneccesary flags

- CHANGES.md
- exec/Main.hs
- package.yaml
- src-files/def-config.yaml
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Core.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/System.hs
- src/Xrefcheck/Verify.hs
Problem: it is often a case that in CI we copy xrefcheck repository into
the verified project, and we want to exclude folder with xrefcheck from
scan. Considering this in config is not too convenient, better add a CLI
option.
Solution: add this CLI option.
As in config, I call it `not-scanned`, because simpler `excluded` is too
general and it's not obvious what exactly it refers to - the set of
verified files or the set of supposedly non-existing files (in the
latter case references _to_ such files should also be prohibited).
- Fixes partially #19 
- Tests
- …
> Add `ignored` CLI option

- CHANGES.md
- package.yaml
- stack.yaml
- stack.yaml.lock
Problem: lootbox is not uploaded to hackage, so when we upload
xrefcheck, its build on hackage fails.
Solution: we can use `mixins` feature to set Universum as prelude
without any intermediate packages.
This seems to be supported even by quite old versions of stack, like
1.7.3, so that should not bring build problems in most cases.
Fixes #30
- Tests
- Haddock
and
> Avoid loot-prelude dependency

- package.yaml
Problem: after we started using mixins feature, generated .cabal file
requires cabal 2.0. Attempt to upload our package to Hackage now reports
an error, saying that `autogen-modules` section have to mention `Path_*`
files.
Solution: add `Paths_xrefcheck` to `generated-other-modules` section of
`package.yaml`.
- Tests
- Haddock
and
> Mention 'Path_*` module in `package.yaml`

- CHANGES.md
- package.yaml
- src/Xrefcheck/Scanners.hs
Problem: `autoexporter` is used in one place to re-export one module.
Probably one day it will re-export more, but at this point it's really
overkill.
Moreover, it causes Hackage build to fail for the reasons mentioned
here:
https://github.com/haskell/hackage-server/issues/821
Solution: stop using it, re-export manually.
None
- Tests
- Haddock
and
> Drop autoexporter usage

- release/default.nix
Release script is broken. Fix it.
Also instead of tarball, add the binary itself to the artifacts.
None
- Tests
- Haddock
and
> Fix release

- CHANGES.md
- exec/Main.hs
- package.yaml
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/System.hs
Problem: we have two major use cases:
1. Using xrefcheck in CI, in this case it is annoying for devops to
always pass mostly always reasonable `--no-progress` option.
2. Using it locally, here we want progress bar to be enabled by default
so that user could run `xrefcheck` without any options most of the time.
Solution:
Detect whether are we running in CI and use the respective default for
whether progress bar should be displayed.
Detecting whether we are within CI is possible using `CI` env variable,
at least Github actions, Gitlab CI and Buildkite pass this env.
`--no-progress` option still can be passed if user wants to suppress
progress bar in local run. The opposite `--progress` seems to also make
sense, because in case if high timeouts are set, user probably wants to
track progress …
> Disable progress bar in CI automatically

- .buildkite/pipeline.yml
- README.md
- docker/default.nix
Having a docker image built and uploaded is vital for a tool like xrefcheck. Docker is the universal "package manager" for CIs.
None
- Tests
- Haddock
and
> Add ability to build with docker

- README.md
Problem: @gromakovsky has recently implemented a github action which
adds xrefcheck pass to CI and it resides in a separate repository, we
want it to be visible in our documentation here.
Solution: mention it in `Usage` section.
- Tests
- Haddock
and
> [#40] Mention GitHub action in `README`

- nix/sources.json
- nix/sources.nix
- xrefcheck.nix
Fixes a typo which caused pins for hackage.nix and stackage.nix to be ignored, and bumps hackage and stackage indexes
Trying to update nixpkgs and haskell.nix broke windows build, so they are not updated in this PR. But we should deal with this at some point if we want to keep dependencies fresh. The error can be seen here: https://buildkite.com/serokell/xrefcheck/builds/305#1f85a7f7-18eb-4000-a09d-bf57ab513742/63-125. I found that it is caused by a commit in nixpkgs which updates `mingw-w64`, because reverting this commit fixes the build: https://github.com/nixos/nixpkgs/commit/8b89e0494c5afc511df5463a413c340b43f73ca9
https://issues.serokell.io/issue/OPS-1023 …
> CI: fix pinning hackage and stackage, update hackage and stackage indexes

- README.md
Problem: there seems to be another popular tool for HTMLs verification
called `linkcheck`, it is stated to be way better than
`broken-link-checker`.
Solution: replace `broken-link-checker` mention with `linkcheck`, say
that there are other solutions to this problem.
Also make the paragraph a bit more clear in general.
- Tests
- Haddock
and
> Update README section with comparison

- .buildkite/pipeline.yml
- CHANGES.md
- README.md
- package.yaml
- src-files/def-config.yaml
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Scanners/Markdown.hs
- src/Xrefcheck/Util.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/IgnoreAnnotationsSpec.hs
- tests/Test/Xrefcheck/IgnoreRegexSpec.hs
- tests/markdowns/with-annotations/ignore_file.md
- tests/markdowns/with-annotations/ignore_link.md
- tests/markdowns/with-annotations/ignore_paragraph.md
- tests/markdowns/with-annotations/no_link.md
- tests/markdowns/with-annotations/no_paragraph.md
- tests/markdowns/with-annotations/unexpected_ignore_file.md
- tests/markdowns/with-annotations/unrecognised_option.md
- tests/markdowns/without-annotations/all_checked.md
- tests/markdowns/without-annotations/all_ignored.md
Sometimes we want to ignore some global links in markdown files. The reasons can be different. For example, we know that CI runner does not have the certain level of access. Or we just want to have broken link in our markdown. This PR adds a couple of ways to do it.
**The first** is about including links we want to ignore in config file. It enables including not only links, but regular expressions for them.
Example:
If you want to ignore https://gitlab.com/morley-framework/morley/-/issues/new and https://gitlab.com/morley-framework/morley/-/merge_requests/new, you should include these lines in your config yaml file (`src-files/def-config.yaml` by default):
```
ignoreRefs:
- https://gitlab.com/morley-framework/morley/-/(issues|merge_requests)/new
```
If you don't want any link in your …
> Ignoring global links in markdown files

- .buildkite/pipeline.yml
- README.md
- ci.nix
- nix/sources.json
- src-files/def-config.yaml
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Scanners/Markdown.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/IgnoreAnnotationsSpec.hs
- tests/Test/Xrefcheck/IgnoreRegexSpec.hs
- xrefcheck.nix
Adds trailing whitespace check from serokell.nix to the pipeline. I've put it into ci.nix file and moved some other nix expressions used in buidlkite there, and I had to refactor nix a bit to use `cleanGit` from `haskell.nix` for the check
https://issues.serokell.io/issue/OPS-1178
- Tests
- Haddock
and
> Add trailing whitespace check to CI

- .buildkite/pipeline.yml
- scripts/upload-docker-image.sh
The previous way of uploading images to dockerhub exposed our password.
Prevent this from happening by using a separate script instead of calling
skopeo directly.
> Fix docker image upload

- src/Xrefcheck/Scanners/Markdown.hs
- tests/Test/Xrefcheck/AnchorsSpec.hs
- tests/Test/Xrefcheck/IgnoreAnnotationsSpec.hs
- tests/Test/Xrefcheck/Util.hs
- tests/markdowns/without-annotations/non_stripped_spaces.md
Problem: 
A header name with its custom anchor appended after the octothorpe symbol(s) is parsed with the leading spaces present, thus generating an anchor from it will result in having a leading hyphen prepended to its beginning.
Solution: 
Having retrieved the header name, strip it to eradicate the leading spaces. This will result in the correct generation of the anchor which won't contain a hyphen at its beginning.
Resolves #72 by applying `Data.Text.strip` to the extracted name of either a link or a header in `nodeExtractText`.
- Tests
- …
> [#72] Fix anchor generation of headers with spaces

- CHANGES.md
- package.yaml
- src/Xrefcheck/Scanners/Markdown.hs
- tests/Test/Xrefcheck/AnchorsInHeadersSpec.hs
- tests/Test/Xrefcheck/AnchorsSpec.hs
- tests/markdowns/without-annotations/anchors_in_headers.md
Problem:
Currently `xrefcheck` ignores HTML-anchors in headers.
Solution:
When traversing node tree, go into `HEADER` subnodes as well.
Resolves #62 
- Tests
- Haddock
and
> [#62] Add anchor recognition in headers

- .stylish-haskell.yaml
- exec/Main.hs
- links-tests/Main.hs
- links-tests/Test/Xrefcheck/FtpLinks.hs
- package.yaml
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Command.hs
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Core.hs
- src/Xrefcheck/Orphans.hs
- src/Xrefcheck/Progress.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/Scanners/Markdown.hs
- src/Xrefcheck/System.hs
- src/Xrefcheck/Util.hs
- src/Xrefcheck/Verify.hs
- tests/Main.hs
- tests/Test/Xrefcheck/AnchorsInHeadersSpec.hs
- tests/Test/Xrefcheck/AnchorsSpec.hs
- tests/Test/Xrefcheck/ConfigSpec.hs
- tests/Test/Xrefcheck/IgnoreAnnotationsSpec.hs
- tests/Test/Xrefcheck/IgnoreRegexSpec.hs
- tests/Test/Xrefcheck/LocalSpec.hs
- tests/Test/Xrefcheck/TrailingSlashSpec.hs
- tests/Test/Xrefcheck/Util.hs
- tests/markdowns/with-annotations/ignore_link.md
Problem: data collection is a function that calls itself 5 screens below the place it starts and is a pile of different, but unrelated actions, performed simultaneously.
Solution: divide the pile into parts and then combine parts externally.
1) The `xrefcheck: ignore X` functionality is implemented as a separate function.
3) The data collection is a fold over the tree, and other reducers can be connected.
`Anchor`/`Reference` colelctor fits into one screen now.
```haskell
foldNode :: (Monoid a, Monad m) => (Node -> m a) -> Node -> m a
```
Runs the provided action, collects the results.
None, preparing for #64 
checkmark indicating that you are sure it is dealt with (be …
> Refactor data collection.

- .reuse/dep5
- nix/sources.json
- package.yaml
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Config/Default.hs
- stack.yaml
- stack.yaml.lock
- tests/Test/Xrefcheck/ConfigSpec.hs
- tests/configs/github-config.yaml
I updated stack resolver to lts 19.13, which uses ghc 9.0.2 and update haskell.nix configuration files, so `nix-build` working with new resolver. I moved up template-haskell declarations in Xrefcheck,Config module, because in ghc 9.0.2 were changed rules of module division by TH, and these FromJSON instances were out of scope of `defConfig` function.
- Fixed #107
> [#107] Update stack resolver to the newer version

- .buildkite/pipeline.yml
- .hlint.yaml
- links-tests/Test/Xrefcheck/FtpLinks.hs
- package.yaml
- src/Xrefcheck/Progress.hs
- src/Xrefcheck/Scanners/Markdown.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/AnchorsSpec.hs
- xrefcheck.nix
I added hlint and weeder configuration files, fixed all useful hints of these tools and add them to the CI pipeline, so we can handle lints and redundant dependencies automatically.
- Fixed  #105
> [#105] Add hlint and weeder support

- tests/golden/check-localhost/check-localhost.md
- tests/golden/check-localhost/expected.gold
Added 20000 port to all links in golden tests and updated expectation
- Fixed #103 by adding ports
> [#103] Specify port in golden test links instead of default one

- CHANGES.md
- package.yaml
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Config/Default.hs
- src/Xrefcheck/Core.hs
- src/Xrefcheck/Progress.hs
- src/Xrefcheck/Util.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/TooManyRequestsSpec.hs
- tests/configs/github-config.yaml
- tests/golden/check-cli/config-no-scan-ignored.yaml
- tests/golden/check-localhost/config-check-disabled.yaml
- tests/golden/check-localhost/config-check-enabled.yaml
Problem: The current version of xrefcheck handles the HTTP responses
with the 429 status code just like every other error, when it is
possible to try and eliminate the occurrences of such errors within the
program itself.
Solution: Each time the result of performing a request on a given link
is a 429 error, retrieve the Retry-After information, describing the
delay (in seconds), from the headers of the HTTP response, or,
alternatively, use a configurable default value if the Retry-After
header is absent, and rerun the request after an amount of time
described by the said value had passed. Only after the number of retries
had reached its limiting value, which, as of right now, is not
configurable and is hardcoded, is when the 429 error is converted into
becoming 'unfixable', and any …
> [#31] Handle the "429 too many requests" errors

- src/Xrefcheck/CLI.hs
Updated help message. Now list of git repository types is listed separated by |. allFlaviors is chosen as source of truth in this case.
- Fixed #113
> [#113] Improve error message of dump-config option

- package.yaml
- src/Xrefcheck/Scanners/Markdown.hs
- tests/golden/check-html/check-html.md
- tests/golden/check-html/check.html.bats
Replace manual parsing using Text combinators with tagsoup library, that takes care about compatibility with HTML specification.
- Fixed #95
> [#95] Support HTML tag parsing compatible with HTML spec

- CHANGES.md
- README.md
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Config/Default.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/IgnoreRegexSpec.hs
- tests/configs/github-config.yaml
Makes `ignoreRefs` a required parameter in the config file.
Fixes #126
- Tests
- Haddock
and
> [#126] Make `ignoreRefs` a required parameter

- CHANGES.md
- src/Xrefcheck/Scanners/Markdown.hs
- tests/Test/Xrefcheck/AnchorsInHeadersSpec.hs
- tests/markdowns/without-annotations/anchors_in_headers_with_id_attribute.md
Add support for the `id` attribute, while retaining support for the `name` attribute.
Fixes #94
- Tests
- Haddock
and
> [#94] Add support for the `id` attribute in anchors

- CHANGES.md
- src/Xrefcheck/Util.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/TooManyRequestsSpec.hs
This adds some bytes to parse `Retry-After` headers as dates for `429: Too many requests`
Fixes #99 
- Tests
- Haddock
and
> [#99] Support `Retry-After` headers with dates

- CHANGES.md
- package.yaml
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/URIParsingSpec.hs
Problem: The current version of xrefcheck doesn't allow the square
brackets and some other special characters, like the angle brackets and
the curly brackets, to be present in the URLs, even in the query
strings, as they need to be percent-encoded first.
Solution: Allow some of the reserved characters, like the brackets, to
be present in the query strings of the URLs.
There exist two main standards of URL parsing: RFC 3986 and the Web
Hypertext Application Technology Working Group's URL standard. Ideally,
we want to be able to parse the URLs in accordance with the latter
standard, because it provides a much less ambiguous set of rules for
percent-encoding special characters, and is essentially a living
standard that gets updated constantly.
We allow these characters to be present in the …
> [#49] Allow certain reserved characters in the URLs

- .buildkite/pipeline.yml
- CHANGES.md
- README.md
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Config/Default.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/System.hs
- src/Xrefcheck/Verify.hs
- tests/configs/github-config.yaml
- tests/golden/check-cli/check-cli.bats
- tests/golden/check-ignored/check-ignored.bats
- tests/golden/check-ignored/config-ignored.yaml
- tests/golden/check-ignored/to-ignore/inner-directory/broken_annotation.md
- tests/golden/check-notScanned/check-notScanned.bats
- tests/golden/check-notScanned/config-directory.yaml
- tests/golden/check-notScanned/config-full-path.yaml
- tests/golden/check-notScanned/config-nested-directories.yaml
- tests/golden/check-notScanned/config-wildcard.yaml
- tests/golden/check-notScanned/expected.gold
- tests/golden/check-notScanned/notScanned/inner-directory/bad-reference.md
Problem: The `virtualFiles` config option supports glob patterns. On the
other hand, `ignored` only supports exact matches and `notScanned`
mathches on prefixes. There is also a bug where `ignored` does not
ignore files if they contain broken xrefcheck annotations.
Solution: Add support for glob patterns to `ignored` and
`notScanned`. Filter ignored files before parsing their contents.
Fixes #77
- Tests
- Haddock
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971ab …
> [#77] Add support for glob patterns to `ignored` and `notScanned`

- tests/golden/check-virtualFiles/check-virtualFiles.bats
- tests/golden/check-virtualFiles/check-virtualFiles.md
- tests/golden/check-virtualFiles/config-virtualFiles.yaml
- tests/golden/check-virtualFiles/expected.gold
- tests/golden/check-virtualFiles/one/file.md
Problem: The `virtualFiles` config allows the user to use glob patterns
to specify files that do not physically exist in the repository but
should be treated as existing nevertheless. However, we do not yet
have any around our usage of glob patterns. We should write some to
1) ensure it behaves in a sensible way even in corner cases and 2)
document  the behaviour.
Solution: Add tests that document how the `virtualFiles` glob paterns work.
Fixes #76 
- Tests
- Haddock
of Public …
> [#76] Add tests for `virtualFiles` glob patterns 

- CHANGES.md
- package.yaml
- src/Xrefcheck/Command.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/Scanners/Markdown.hs
- tests/Test/Xrefcheck/AnchorsInHeadersSpec.hs
- tests/Test/Xrefcheck/IgnoreAnnotationsSpec.hs
- tests/Test/Xrefcheck/IgnoreRegexSpec.hs
- tests/Test/Xrefcheck/TrailingSlashSpec.hs
- tests/Test/Xrefcheck/Util.hs
- tests/golden/check-ignored/check-ignored.bats
- tests/golden/check-ignored/expected.gold
- tests/golden/check-scan-errors/check-scan-errors.bats
- tests/golden/check-scan-errors/check-scan-errors.md
- tests/golden/check-scan-errors/check-second-file.md
- tests/golden/check-scan-errors/expected.gold
- tests/golden/check-scan-errors/no_link_eof.md
- tests/golden/check-scan-errors/no_paragraph_eof.md
- tests/markdowns/with-annotations/unrecognised_option.md
Problem: Currently, xrefcheck fails immediately after the first observed error because `die` is used right in `markdownScanner` What we want is dumping all the errors from different markdowns and then print them as a final xrefcheck's result together with the broken links. Also, despite the fact that in the `makeError` function we have 4 error messages, 2 of them are not reported, and the test case that should check this only checks that at least one of the four files throws an error.
https://github.com/serokell/xrefcheck/blob/1b0b8d5fdbae53438df051bf3d57f91df9e9c125/tests/Test/Xrefcheck/IgnoreAnnotationsSpec.hs#L18-L20
Solution: Make xrefcheck to report all errors. Add `ScanError` type and propagate errors to report all of them, rather than failing immediately after the first error is …
> [#56] Dump all the errors from different files

- CHANGES.md
- links-tests/Test/Xrefcheck/FtpLinks.hs
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Command.hs
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/Scanners/Markdown.hs
- src/Xrefcheck/Util.hs
- tests/Test/Xrefcheck/ConfigSpec.hs
- tests/Test/Xrefcheck/Util.hs
Problem: In #126 we made the `ignoreRefs` option required (to match the other options). However, having it optional is better for backwards-compatibility and to help users migrate to newer xrefcheck versions.
Solution: Make all config options optional.
Fixes #156 
- Tests
- Haddock
and
under the "Unreleased" section to a new section …
> [#156] Make all config options optional

- .github/pull_request_template.md
Problem: Turns out the release instructions are not entirely accurate.
In order for `xrefcheck-action` to work, the `xrefcheck` release page must have the linux binary and the windows zip file attached.
Turns out the recommended way to do this is to edit the "auto-release" page created by the "Create a pre-release" CI step, see the instructions here:
https://raw.githubusercontent.com/serokell/scratch/release-binary/scripts/release-binary.sh
Solution: edit the release checklist to include these instructions.
None
- Tests
- …
> [Chore] Update release instructions

- .gitignore
- CHANGES.md
- src/Xrefcheck/Util.hs
- tests/Test/Xrefcheck/ConfigSpec.hs
- tests/golden/check-virtualFiles/config-virtualFiles.yaml
Problem: As in #140, unrecognised fields of config are ignored. We want to raise an error instead
Solution: change aeson options for config and it's subtypes, now it throws errors like
```
xrefcheck: Aeson exception:
Error in $: Unknown fields: ["traversajhl"]
```
Fixes #140
- Tests
- Haddock
and
> [#140] Unknown field errors

- .buildkite/pipeline.yml
- .stylish-haskell.yaml
- Makefile
- ci.nix
- ftp-tests/Test/Xrefcheck/FtpLinks.hs
- nix/sources.json
- scripts/validate-stylish.sh
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Command.hs
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Core.hs
- src/Xrefcheck/Orphans.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/System.hs
- tests/Test/Xrefcheck/AnchorsInHeadersSpec.hs
- tests/Test/Xrefcheck/AnchorsSpec.hs
- tests/Test/Xrefcheck/ConfigSpec.hs
- tests/Test/Xrefcheck/IgnoreAnnotationsSpec.hs
- tests/Test/Xrefcheck/IgnoreRegexSpec.hs
- tests/Test/Xrefcheck/TooManyRequestsSpec.hs
- tests/Test/Xrefcheck/TrailingSlashSpec.hs
Problem: We should add stylish-haskell and shellcheck to our pipline.
Solution: Add stylish-haskell and shellcheck. Use stylish-haskell on repo.
Fixes #135 
- Tests
- Haddock
and
> [#135] CI: add stylish-haskell and shellcheck

- .github/pull_request_template.md
- package.yaml
- stack.yaml
- stack.yaml.lock
This PR:
* Adds an item to the release checklist so we won't forget to upload xrefcheck to hackage.
* Removes unnecessary extra-deps from stack.yaml
* We accidentally removed the `base` constraint in #97 - but this is needed to build a release tarball with `stack sdist`, so let's add it back in.
None
- Tests
- Haddock
and
under the …
> [Chore] Update release checklist & fix base constraint

- src/Xrefcheck/Config.hs
- tests/golden/check-cli/config-no-scan-ignored.yaml
- tests/golden/check-ignoreRefs/config-check-disabled.yaml
- tests/golden/check-ignoreRefs/config-check-enabled.yaml
- tests/golden/check-ignored/config-ignored.yaml
- tests/golden/check-notScanned/config-directory.yaml
- tests/golden/check-notScanned/config-full-path.yaml
- tests/golden/check-notScanned/config-nested-directories.yaml
- tests/golden/check-notScanned/config-wildcard.yaml
- tests/golden/check-virtualFiles/config-virtualFiles.yaml
Problem: In #159 we made all config fields optional. Now we can trim redundant fields from test configs.
Solution: Trim redundant config fields. Also slightly refactor `overrideVerify` function to make it more readable.
Fixes #156 
- Tests
- Haddock
and
* Change …
> [#156] Trim redundant config fields from test configs

- .hlint.yaml
- CHANGES.md
- package.yaml
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Command.hs
- src/Xrefcheck/Core.hs
- src/Xrefcheck/Progress.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/Util.hs
- src/Xrefcheck/Util/Colorize.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/IgnoreRegexSpec.hs
Problem: output of xrefcheck contains ANSI-colored text,
which is bad when we redirect output to file
or when our terminal is not supporting colors.
Colorising is performed in `Buildable` instances of various types,
so we can't just pass some extra flag here
Solution: add CLI  option `--no-color`
Create `colorIfNeeded` and `styleIfNeeded` functions that have
`Data.Reflection.Given ColorMode` constraint, and replace all usages of
`color` nd `style` by them, adding new
constraint to instances.
Fixes #185 
- Tests
- …
> [#185] Add CLI option to disable output coloring

- src/Xrefcheck/Scan.hs
- src/Xrefcheck/Scanners/Markdown.hs
- tests/Test/Xrefcheck/IgnoreAnnotationsSpec.hs
Problem: Currently, сonstructor None from `IgnoreMode` is used to represent two distinct things: 1) no "ignore mode" is currently set 2) unrecognized "ignore mode" is found. It would make more sense to change `getIgnoreMode`. Instead of returning `Maybe IgnoreMode`, it should return type `GetIgnoreMode` with 3 possible constructor: `NotAnAnnotation`, `ValidMode IgnoreMode`, `InvalidMode Text`.
Solution: Remove `None` from `IgnoreMode`, make `getIgnoreMode` to return `GetIgnoreMode`, use `Maybe Ignore` as scan state where `Nothing` represents no mode is currently set.
Fixes #151
Fixes #167 …
> [#151] [#167] Refactor `IgnoreMode`

- tests/golden/check-local-refs/config-with-virtual-files.yaml
- tests/golden/check-local-refs/dir1/dir2/d2f1.md
- tests/golden/check-local-refs/dir1/dir2/d2f3.yaml
- tests/golden/check-local-refs/expected1.gold
- tests/golden/check-local-refs/expected2.gold
- tests/golden/check-local-refs/expected3.gold
Problem: there is no tests for links to directories and non-markdown files. Also we aren't testing that links are case sensetive
Solution: add such tests to `check-local-refs`, also check that only links to directory are allowed to have trailing slash,
e.g. `a.md/` is bad and `dir1/` is ok
Fixes #165 
Fixes #192 
- Tests
- Haddock
and
> [#165] [#192] Add tests for specific cases of local references

- CHANGES.md
- src/Xrefcheck/Scanners/Markdown.hs
- tests/Test/Xrefcheck/AnchorsInHeadersSpec.hs
- tests/Test/Xrefcheck/AnchorsSpec.hs
- tests/Test/Xrefcheck/IgnoreAnnotationsSpec.hs
- tests/Test/Xrefcheck/Util.hs
- tests/markdowns/with-annotations/ignore_link.md
Problem:
Currently `ignore link` annotation works for a  first link after it (in a whole  file). That can be bad for user,
e.g. he may forgot to delete this annotation, and now it ignores link in some random place
Solution:
Throw scan errors when `ignore link` is not followed by a node with link. To do this, we need to increase amount  of context in `ScannerM`.
Examples:
This is now bad and reported with message `Expected a LINK after "ignore link" annotation`:
```markdown
foo
bar [link](link)
```
Those are still OK:
```markdown
foo [link](link)
```
```markdown
Foo  bar [link](link)
```
Fixes #150 
checkmark indicating that you are sure it is dealt with (be that by …
> [#150] Change `ignore link` behavior

- CHANGES.md
- package.yaml
* Added support for footnotes.
* Tighter git integration. Xrefcheck now ignores all files not being tracked by git.
References _from_ these files will not be checked; references _to_ these files will fail verification.
* Added the `--no-color` option to disable ANSI-colored text.
* Xrefcheck will no longer fail when it encountes a local link to a file with a trailing slash.
* Xrefcheck was accidentally verifying links to files matching the `--ignored` CLI option or the `ignored` config option.
This has been fixed; such links will now be reported as invalid.
* Do not print ANSI-colored text when the terminal doesn't support coloring.
* Fail if the config file contains unknown fields / field names with typos.
* Fixed async bug where the output would sometimes [look like a …
> v0.2.2 release

- CHANGES.md
- src/Xrefcheck/Scanners/Markdown.hs
- tests/golden/check-autolinks/check-autolinks.bats
- tests/golden/check-autolinks/file-with-autolinks.md
Problem: GitHub renders "implicit" links like `visit www.google.com` as links, but we don't check them, since cmark-gfm renders them as text
Solution: add `autolink` extension to `cmark-gfm`, so both `www.google.com`  and `https://google.com`
will be parsed as link and successfuly verified
Also now we use newest cmark-gfm form hackage (not from GitHub)
Fixes #157
- Tests
- Haddock
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contr …
> [#157] Add support for autolinks

- CHANGES.md
- ftp-tests/Test/Xrefcheck/FtpLinks.hs
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Command.hs
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Config/Default.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/ConfigSpec.hs
- tests/Test/Xrefcheck/IgnoreRegexSpec.hs
- tests/Test/Xrefcheck/TooManyRequestsSpec.hs
- tests/Test/Xrefcheck/TrailingSlashSpec.hs
- tests/configs/github-config.yaml
- tests/golden/check-cli/config-no-scan-ignored.yaml
- tests/golden/check-ignoreRefs/config-check-disabled.yaml
- tests/golden/check-ignoreRefs/config-check-enabled.yaml
- tests/golden/check-ignored/config-ignored-bad-path-absolute.yaml
- tests/golden/check-ignored/config-ignored-malformed-glob.yaml
- tests/golden/check-ignored/config-ignored.yaml
- tests/golden/check-local-refs/config-with-virtual-files.yaml
- tests/golden/check-notScanned/config-directory.yaml
- tests/golden/check-notScanned/config-full-path.yaml
- tests/golden/check-notScanned/config-nested-directories.yaml
- tests/golden/check-notScanned/config-wildcard.yaml
- tests/golden/check-virtualFiles/config-virtualFiles.yaml
Problem: At the moment, the config yaml is organized in 3 top-level keys: `traversal`, `verification` and `scanners`. However, the distinction between the "traversal" and the "verification" stages is not relevant to the user. This is entirely an internal concern.
Solution: Reorganize yaml config options under `exclusions`, `networking` and `scanners`.
Fixes #170 
Fixes #119 
- Tests
- Haddock
of Public …
> [#170] [#119] Reorganize top-level config keys

- tests/golden/check-cli/check-cli.bats
- tests/golden/check-footnotes/expected.gold
- tests/golden/check-git/check-git.bats
- tests/golden/check-ignore/check-ignore.bats
- tests/golden/check-ignore/expected.gold
- tests/golden/check-ignoreExternalRefsTo/expected.gold
- tests/golden/check-ignoreLocalRefsTo/expected.gold
- tests/golden/check-ignoreRefsFrom/check-ignoreRefsFrom.bats
- tests/golden/check-local-refs/expected1.gold
- tests/golden/check-local-refs/expected2.gold
- tests/golden/check-local-refs/expected3.gold
- tests/golden/check-scan-errors/expected.gold
- tests/golden/helpers.bash
Problem: Right now, our bats tests ignore empty lines and
leading/trailing whitespace differences between the expected output and
the actual output.
However, this could lead to accidental bugs in xrefcheck's output.
Trailing whitespace isn't very concerning (except when it's excessive
and it causes the terminal to line-wrap), but additional/missing empty
lines and leading whitespace can lead to significant changes.
Solution: Let's make these tests sensitive to empty lines and leading
whitespace.
Fixes #206
- Tests
- …
> [#206] Make bats tests space-sensitive

- src/Xrefcheck/Command.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/Verify.hs
- tests/golden/check-anchors/check-anchors.bats
- tests/golden/check-autolinks/check-autolinks.bats
- tests/golden/check-cli/check-cli.bats
- tests/golden/check-footnotes/expected.gold
- tests/golden/check-git/check-git.bats
- tests/golden/check-ignore/check-ignore.bats
- tests/golden/check-ignore/expected.gold
- tests/golden/check-ignoreExternalRefsTo/expected.gold
- tests/golden/check-ignoreLocalRefsTo/expected.gold
- tests/golden/check-ignoreRefsFrom/check-ignoreRefsFrom.bats
- tests/golden/check-images/expected.gold
- tests/golden/check-local-refs/expected1.gold
- tests/golden/check-local-refs/expected2.gold
- tests/golden/check-local-refs/expected3.gold
- tests/golden/check-scan-errors/expected.gold
Problem: xrefcheck's output contains many redundant newlines, so it takes more display space than it could.
For list of places where such newlines appear, see #208
Solution: don't print redundant newlines, so output is more compact. Since tests are newline-sensetive, I've checked that now there are no extra  (e.g. 2 ajacent) blank lines in `expected` part of tests.
Fixes #208
- Tests
- Haddock
of Public …
> [#208] Remove exessive newlines from output

- .hlint.yaml
- package.yaml
- src/Xrefcheck/Command.hs
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Core.hs
- src/Xrefcheck/Scanners/Markdown.hs
- src/Xrefcheck/Util.hs
- src/Xrefcheck/Util/Interpolate.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/TooManyRequestsSpec.hs
- tests/Test/Xrefcheck/TrailingSlashSpec.hs
- tests/golden/check-anchors/check-anchors.bats
- tests/golden/check-autolinks/check-autolinks.bats
- tests/golden/check-images/expected.gold
- tests/golden/check-local-refs/expected1.gold
- tests/golden/check-local-refs/expected2.gold
- tests/golden/check-local-refs/expected3.gold
- tests/golden/helpers.bash
Problem: bats tests are not space sensetive
Solution: remove trailing spaces from xrefcheck output (see next problems), remove `--ignore-trailing-space` from `assert_diff`
Problem: there are lines containing only spaces in xrefcheck's output, because `Fmt.indentF` "indents" empty lines too.
Solution: add `Xrefcheck.Util.indentF_` function that is not indenting empty lines. Same for `Fmt.blockListF`
Problem: when there is a current file link `[a](#b)`, it is printed like
```
- text: "a"
- link: (trailing space here)
- anchor: b
```
Solution: as in case when there is no anchor, print `link: -` instead
Fixes #213 
checkmark indicating that you are sure it is dealt with …
> [#213] Do not print trailing whitespaces

- .buildkite/pipeline.yml
- package.yaml
- src/Xrefcheck/Command.hs
- src/Xrefcheck/Core.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/Verify.hs
Currently, if xrefcheck is interrupted, it's not displaying any `VerifyError`s, even if it has already found some. When we found error, we are notifying user via progress bar, but he must wait checking of all references to see it
(and it can be long enough).
Solution: when xrefcheck is interrupted, display all errors we have already found and a number of
checked references.
To do this, we need to modify `forConcurrentlyCaching` behaviour on exceptions.
Fixes #89
- Tests
- …
> [#89] Handle user interrupts

- CHANGES.md
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Command.hs
- src/Xrefcheck/Core.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/IgnoreRegexSpec.hs
- tests/Test/Xrefcheck/TrailingSlashSpec.hs
- tests/golden/check-git/check-git.bats
Problem: after 0.2.2 release, xrefcheck cares only about files that were added to Git. That can be confusing for users (see #200)
Solution:
If a scannable (currently it means markdown) file is not ignored (by git or via config) and not tracked by git, print a warning to stderr while scanning repo.
If a link target such file, change error message from "file not exists" to `Link target is not tracked by Git`
Suggest user to run "git add" before running xrefcheck in both cases.
To do this, I've changed the `RepoInfo` type, so it also contains information about untracked files now.
Also add CLI option 1--include-untracked` to treat such files as existing.
Fixes #200 …
> [#200] Warnings about files that weren't added to git yet

- .buildkite/pipeline.yml
- README.md
Improved the readme and fixed several problems:
* Mention support for GitLab - this is important and wasn't mentioned anywhere.
* Add a FAQ clarifying how xrefcheck behaves in some important situations. 
* We don't need to get into a lot of detail about the syntax of the `xrefcheck: ignore` annotations, where they're allowed and where they're not. A general idea and a couple of examples are more than enough.
* Added the backlink `[↑](#xrefcheck)` where it was missing.
* Fixed inconsistent level headers: we we're using `###` where we should be using `##`
* `nix run` should now be `nix shell`
* Add a link to `tests/configs/github-config.yaml` which contains a list of all supported config options.
* Instead of mentioning GitHub Actions in the "usage" section and nix in a separate section, …
> [#147] Update readme

- exec/Main.hs
- package.yaml
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Config/Default.hs
- src/Xrefcheck/Core.hs
- src/Xrefcheck/Scanners/Markdown.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/ConfigSpec.hs
Problem:
We have a function `defConfigText :: Flavor -> ByteString` that uses  `fillHoles` to modify `defConfigUnfilled`.
This is a bit error-prone and very complicated way to have a `ByteString` with parametric blocks. Also using `ByteString` instead of `Text` to store text leads to CRLF-related issues when launched on Windows.
Solution:
Remove `fillHoles` and `defConfigUnfilled`,
`defConfigText` creates a `Text` using `nyan-interpolation`.
We have test that proves that config string for `GitHub` flavor wasn't accidently changed.
Fixes #223
- Tests
- …
> [#223] Use nyan-interpolation for `defConfigText`

- CHANGES.md
- src/Xrefcheck/Core.hs
- src/Xrefcheck/Verify.hs
- tests/golden/check-anchors/check-anchors.bats
- tests/golden/check-local-refs/dir1/dir2/d2f1.md
- tests/golden/check-local-refs/expected1.gold
- tests/golden/check-local-refs/expected2.gold
- tests/golden/check-local-refs/expected3.gold
Problem: We have found that the current tag for local file references, "current file", may lead to ambiguities.
Solution: Rename the tag that we use for local file references to be "file-local" instead.
Fixes #228 
- Tests
- Haddock
and
> [#228] Rename local file reference tag

- CHANGES.md
- README.md
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/RedirectRequestsSpec.hs
- tests/Test/Xrefcheck/TooManyRequestsSpec.hs
- tests/Test/Xrefcheck/UtilRequests.hs
- tests/golden/check-autolinks/check-autolinks.bats
Problem: Xrefcheck currently always follows redirect links.
Solution: We are changing its default behaviour regarding redirect links to fail and report permanent redirects, and to pass for temporary redirects. Further PRs will allow the user to configure other policies.
Fixes #218
Relates #25
- Tests
- Haddock
and
> [#218] Change redirects default behaviour

- CHANGES.md
- README.md
- package.yaml
- src/Xrefcheck/Core.hs
- src/Xrefcheck/Progress.hs
- src/Xrefcheck/Verify.hs
- tests/golden/check-case-sensitivity/a.md
- tests/golden/check-case-sensitivity/check-case-sensitivity.bats
- tests/golden/check-case-sensitivity/config-github.yaml
- tests/golden/check-case-sensitivity/config-gitlab.yaml
- tests/golden/check-case-sensitivity/expected1.gold
- tests/golden/check-case-sensitivity/expected2.gold
- tests/golden/check-git/check-git.bats
Problem: Some Markdown flavours such as the GitHub one are case insensitive regarding anchors, but our analysis is currently case sensitive and it produces false positives.
Solution: Support case-insensitivity depending on the configured Markdown flavour. Apply this also to ambiguous and similar anchors detection.
Fixes #211 
- Tests
- Haddock
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) …
> [#211] Case insensitive anchors

- CHANGES.md
- exec/Main.hs
- package.yaml
- src/Xrefcheck/CLI.hs
- tests/Test/Xrefcheck/ConfigSpec.hs
- tests/golden/check-dump-config/.config.yaml
- tests/golden/check-dump-config/.xrefcheck.yaml
- tests/golden/check-dump-config/check-dump-config.bats
Problem: xrefcheck does not allow to print the config to stdout instead of writing it to a file. Also, it is easy to overwrite your changes by mistake by executing the command again.
Solution: provide a `--stdout` flag to print the config to stdout, and do not write it to a file unless a `--force` flag has been included.
Fixes #254 
- Tests
- Haddock
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e …
> [#254] Revise dump-config command

- .hlint.yaml
- ftp-tests/Test/Xrefcheck/FtpLinks.hs
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Command.hs
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Config/Default.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/Scanners/Markdown.hs
- src/Xrefcheck/Util.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/ConfigSpec.hs
- tests/Test/Xrefcheck/RedirectRequestsSpec.hs
- tests/Test/Xrefcheck/TimeoutSpec.hs
- tests/Test/Xrefcheck/TooManyRequestsSpec.hs
- tests/Test/Xrefcheck/UtilRequests.hs
- tests/configs/github-config.yaml
Problem: Currently, getting response timeout immediately results in fail, it's desired to have a possibility to configure retries on timeouts.
Solution: The new ExternalHttpTimeout error is added, which is treated in a similar way as the ExternalHttpTooManyRequests error. A new field is added to the config meaning how many timeouts are allowed. Default value equals to 1.
Fixes #217 
- Tests
- Haddock
of Public …
> [#217] Retry on response timeout

- CHANGES.md
- README.md
- ftp-tests/Test/Xrefcheck/FtpLinks.hs
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Config/Default.hs
- src/Xrefcheck/Data/Redirect.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/Util.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/ConfigSpec.hs
- tests/Test/Xrefcheck/RedirectChainSpec.hs
- tests/Test/Xrefcheck/RedirectConfigSpec.hs
- tests/Test/Xrefcheck/RedirectDefaultSpec.hs
- tests/configs/github-config.yaml
- tests/golden/check-autolinks/check-autolinks.bats
- tests/golden/check-ignoreExternalRefsTo/config-check-disabled.yaml
- tests/golden/check-redirect-parse/bad-code.yaml
- tests/golden/check-redirect-parse/bad-on.yaml
- tests/golden/check-redirect-parse/bad-outcome.yaml
- tests/golden/check-redirect-parse/bad-rule.yaml
- tests/golden/check-redirect-parse/bad-rules.yaml
- tests/golden/check-redirect-parse/bad-to.yaml
- tests/golden/check-redirect-parse/check-redirect-parse.bats
- tests/golden/check-redirect-parse/full-rule.yaml
- tests/golden/check-redirect-parse/no-outcome.yaml
- tests/golden/check-redirect-parse/no-rules.yaml
- tests/golden/check-redirect-parse/only-outcome-on.yaml
- tests/golden/check-redirect-parse/only-outcome-to.yaml
- tests/golden/check-redirect-parse/only-outcome.yaml
Problem: We previously changed the default behaviour of Xrefcheck when following link redirects, but did not provide a way to configure it.
Solution: We are adding a new field in the configuration file to allow writing a list of redirect rules that will be applied to links that match them.
Relates #25 
- Tests
- Haddock
and
> [#25] Redirect links with configuration rules

- src/Xrefcheck/Core.hs
- src/Xrefcheck/Progress.hs
- src/Xrefcheck/Util.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/RedirectChainSpec.hs
- tests/Test/Xrefcheck/RedirectConfigSpec.hs
- tests/Test/Xrefcheck/RedirectDefaultSpec.hs
- tests/Test/Xrefcheck/TimeoutSpec.hs
- tests/Test/Xrefcheck/TooManyRequestsSpec.hs
- tests/Test/Xrefcheck/UtilRequests.hs
Problem: the current progress bar interface is quite low-level and error-prone.
Solution: the proposed solution here modifies both the progress bar internal model and interface by representing progress units by witnesses. It does not require great changes, but the resulting interface is clearer and less error-prone.
Relates #235
- Tests
- Haddock
and
> [#235] Refactor progress bar interface

- CHANGES.md
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Command.hs
- tests/golden/check-color/check-color.bats
- tests/golden/check-color/color.md
- tests/golden/check-color/expected-color.gold
- tests/golden/check-color/expected-no-color.gold
Problem: We noticed that output was not being colorized in GitLab CI due to the current implemented guesses for whether showing colors or not.
Solution: On the one hand, we extend the current guesses to also enable coloring by default when the CI env var is set to true. On the other hand, we also add a new flag, color, which avoids these guesses and enables colors.
I have tried in a GitLab CI project and the output is colored now.
Fixes #237 
- Tests
- Haddock
and
> [#237] Modify coloring options

- CHANGES.md
- src/Xrefcheck/Data/URI.hs
- src/Xrefcheck/Verify.hs
- tests/Test/Xrefcheck/RedirectChainSpec.hs
- tests/Test/Xrefcheck/URIParsingSpec.hs
- tests/Test/Xrefcheck/UtilRequests.hs
- tests/golden/check-autolinks/check-autolinks.bats
Problem: Currently, Xrefcheck can follow redirects with an absolute location link, but it cannot handle relative ones.
Solution: After parsing the location link, obtain the corresponding absolute link by using the original request one.
Fixes #270 
- Tests
- Haddock
and
> [#270] Handle relative redirects

- release/default.nix
Problem: During flakifycation PR `release/default.nix` was missed.
Solution: Update it to use flake outputs.
Fixes #
- Tests
- Haddock
and
* Change the tag and title using the format `vX.Y.Z`.
* Write a summary of all user-facing changes.
* Deselect the "This is …
> [Chore] Update release derivation

- tests/golden/check-symlinks/check-symlinks.bats
The current Windows CI started to fail at some point because it is running within an environment in which symlinks don't work properly.
Having symlinks working on Windows Git Bash has some requirements:
* Enable symlinks during `git for windows` installation, which is [already met](https://github.com/actions/runner-images/blob/win22/20230508.3/images/win/scripts/Installers/Install-Git.ps1#L23).
* Be either running as an admin or having Windows developer mode turned on, which is also already met.
* Use an environment variable to properly enable symlinks, which is being added with this PR.
None
checkmark indicating that you are sure it is dealt with (be that by …
> [Chore] Fix symlinks test on Windows Git Bash

- .github/workflows/autorelease.yml
- flake.lock
- flake.nix
- release/default.nix
Problem: After a recent switch to GitHub Actions, job that creates prerelease suddenly stopped working.
Solution: Switch to the autoreleasing script from serokell.nix which uses 'gh' instead of 'hub'.
Currently based on https://github.com/serokell/serokell.nix/pull/143
Proof that these changes work correctly: https://github.com/serokell/xrefcheck/actions/runs/6250135982/job/16968887140
Fixes #
- Tests
- Haddock
of Public …
> [Chore] Fix autoreleasing CI job

- .github/workflows/autorelease.yml
- .github/workflows/ci.yml
- .github/workflows/danger.yml
- .github/workflows/dockerhub-release.yml
Problem: node16 is now deprecated and github-runner provided by nixpkgs
no longer supports this runtime. However, "actions/checkout@v3" uses
this runtime.
Solution: Update CI pipeline to use "actions/checkout@v4".
> [Chore] Update "actions/checkout"

- .github/workflows/danger.yml
Explicitly pin `ruby` and `danger` versions in CI to avoid the situation when the latest danger version (which is used by the action by default) becomes incompatible with the used ruby version (due to version requirements for some transitive danger dependencies).
An example of such incompatibility: https://github.com/serokell/xrefcheck/pull/294/checks#step:4:15
Fixes #
- Tests
- Haddock
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public …
> [Chore] Update ruby version used in CI to 3.3

- flake.nix
- ftp-tests/Test/Xrefcheck/FtpLinks.hs
- package.yaml
- tests/Main.hs
- tests/Test/Xrefcheck/ConfigSpec.hs
- tests/Test/Xrefcheck/Util.hs
* flake.nix: inherit devShells, so that `nix develop` works
* tests: configurable mock server port to avoid conflicts
With these changes I've been able to build the project and run its tests as follows
```
nix shell nixpkgs#haskellPackages.hpack nixpkgs#cabal-install
nix develop -c $SHELL
hpack
vsftpd \
-orun_as_launching_user=yes \
-olisten_port=2221 \
-olisten=yes \
-oftp_username=$(whoami) \
-oanon_root=./ftp-tests/ftp_root \
-opasv_min_port=2222 \
-ohide_file='{.*}' \
-odeny_file='{.*}' \
-oseccomp_sandbox=no \
-olog_ftp_protocol=yes \
-oxferlog_enable=yes \
-ovsftpd_log_file=./ftp.log &
cabal test ftp-tests --test-options="--ftp-host ftp://127.0.0.1:2221"
cabal test xrefcheck-tests --test-options="--mock-server-port 3001"
```
> [Chore] Update development setup

- .github/workflows/ci.yml
- package.yaml
- stack.yaml
- stack.yaml.lock
- tests/Test/Xrefcheck/RedirectChainSpec.hs
- tests/Test/Xrefcheck/RedirectConfigSpec.hs
- tests/Test/Xrefcheck/RedirectDefaultSpec.hs
- tests/Test/Xrefcheck/TimeoutSpec.hs
- tests/Test/Xrefcheck/TooManyRequestsSpec.hs
- tests/Test/Xrefcheck/Util.hs
Problem: `firefly` depends on `regex-pcre`, which fails to build in certain configurations:
```
regex-pcre > regex-pcre-0.95.0.0: library-dirs: /usr/lib is a relative path which makes no
regex-pcre > sense (as there is nothing for it to be relative to). You can make paths
regex-pcre > relative to the package database itself by using ${pkgroot}. (use --force to
regex-pcre > override)
regex-pcre > regex-pcre-0.95.0.0: dynamic-library-dirs: /usr/lib is a relative path which
regex-pcre > makes no sense (as there is nothing for it to be relative to). You can make
regex-pcre > paths relative to the package database itself by using ${pkgroot}. (use
regex-pcre > --force to override)
```
The problem only occurs with `stack` on Windows. Therefore, there are two possible workarounds: (a) use …
> [Chore] Replace firefly with scotty in tests

- .github/workflows/ci.yml
- flake.lock
- flake.nix
- ftp-tests/Test/Xrefcheck/FtpLinks.hs
- package.yaml
- src/Xrefcheck/CLI.hs
- src/Xrefcheck/Config.hs
- src/Xrefcheck/Core.hs
- src/Xrefcheck/Scan.hs
- src/Xrefcheck/Scanners/Markdown.hs
- src/Xrefcheck/Util.hs
- src/Xrefcheck/Verify.hs
- stack.yaml
- stack.yaml.lock
- tests/Test/Xrefcheck/AnchorsInHeadersSpec.hs
- tests/Test/Xrefcheck/AnchorsSpec.hs
- tests/Test/Xrefcheck/ConfigSpec.hs
- tests/Test/Xrefcheck/IgnoreAnnotationsSpec.hs
- tests/Test/Xrefcheck/IgnoreRegexSpec.hs
- tests/Test/Xrefcheck/RedirectChainSpec.hs
- tests/Test/Xrefcheck/RedirectConfigSpec.hs
- tests/Test/Xrefcheck/RedirectDefaultSpec.hs
- tests/Test/Xrefcheck/TimeoutSpec.hs
- tests/Test/Xrefcheck/TooManyRequestsSpec.hs
- tests/Test/Xrefcheck/TrailingSlashSpec.hs
- tests/Test/Xrefcheck/Util.hs
- tests/Test/Xrefcheck/UtilRequests.hs
This PR updates the Stackage resolver to LTS-22.32 (GHC 9.6.6) and makes the necessary changes to avoid build issues.
Resolves #285
> [Chore] Bump Stackage to LTS-22.32

- tests/Test/Xrefcheck/RedirectChainSpec.hs
- tests/Test/Xrefcheck/RedirectConfigSpec.hs
- tests/Test/Xrefcheck/RedirectDefaultSpec.hs
- tests/Test/Xrefcheck/TimeoutSpec.hs
- tests/Test/Xrefcheck/TooManyRequestsSpec.hs
- tests/Test/Xrefcheck/UtilRequests.hs
In the `withServer` helper, we now use warp's beforeMainLoop callback and an MVar to synchronize threads. This makes the test suite more resilient to spurious failures on systems with slow IO.
> [Chore] Tests: Wait for server to start

- stack.yaml
- tests/golden/check-autolinks/expected.gold
As a result, the reported locations are more precise and the `stack.yaml` has one fewer extra dep.
> [Chore] Update to cmark-gfm-0.2.6

- CHANGES.md
- package.yaml
* #176
+ Enabled `autolink` extension for `cmark-gfm`, so now we're finding strings like `www.google.com` or `https://google.com`, treating them as links and checking.
* #175
+ Reorganize top-level config keys.
* #178
+ Rename exclusion-related config options.
* #183
+ Add support for image links.
* #199
+ Now annotation `` instead of `` should be used to disable checking for links in file, so it's clearer that file itself is not ignored (and links can target it).
* #215
+ Now we notify user when there are scannable files that were not added to Git yet. Also added CLI option `--include-untracked` to scan such files and treat as existing.
* #191
+ Now we consider slash `/` (and only it) as path separator in local links for all OS, so xrefcheck's report is OS-independent
+ Use utf-8 …
> v0.3.0 release

- CHANGES.md
- src/Xrefcheck/Scanners/Markdown.hs
**Problem:** xrefcheck was crashing on repositories containing a large number of Markdown files, reporting the following internal error:
```
openBinaryFile: resource exhausted (Too many open files)
```
**Solution:** use strict file IO (BS.readFile instead of BS.L.readFile) to ensure that file handles are released in a timely fashion.
Fixes #311
> [#311] Fix a "resource exhausted" crash

- src/Xrefcheck/Scan.hs
Use `proc` to avoid the overhead and security considerations of `shell`.
> [Chore] Use `proc` instead of `shell` to call `git`
