serokell/xrefcheck

.github/CONTRIBUTING.md, README.md, src-files/def-config.yaml, src/Crv/Verify.hs
Make README more attractive to an arbitrary user.
[Rendered](https://github.com/serokell/crossref-verifier/tree/martoon/int128-nice-readme#crossref-verifier).
I adjusted it according to my own taste, which though is known to be strage enough to deserve Lebedev's award, so I would appreciate if someone else takes a look.  
I did everything what we discussed before except for committing release
- Tests
- Haddock
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe48 …
=> Improve readme

README.md
I've corrected typos, English, and systematized formatting a little. As I understood, there will be changes that probably invalidate the meaty part of the readme, so I won't touch anything other than this for now. 
- Tests
- Haddock
=> Making readme more readable & typo-free

.github/pull_request_template.md, CHANGES.md, package.yaml
Problem: we are going to release this tool and from that point
it would be nice to maintain its changelog.
Solution: add a simple CHANGES.md and update PR template.
- Tests
- Haddock
=> Add a changelog, require its maintenance

exec/Main.hs, nix/sources.json, package.yaml, stack.yaml
We have cases when attempt to print to stdout failed with
```
Repository data:
crossref-verify: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character)
``` 
This can be fixed via setting handlers encoding to UTF-8.
Tested with `LC_ALL=C`, failure does not occur anymore, though some unusual Unicode characters are replaced with `?`, so it might we generally recommended running this tool with `LC_ALL=en_US.UTF-8`.
- Tests
- Haddock
of Public …
=> Fix encoding issues

package.yaml
Problem: `stack upload` does not like that `base` does not have an
upper bound, it reports an error while checking the package.
Solution: add an upper bound on `base` to prevent people from using a
broken version of this package in case of breaking changes in `base`.
Since we build with stack, our current default is 4.13 (deduced from
the resolver). However, 4.14 does not seem to have any breaking changes
https://hackage.haskell.org/package/base-4.14.0.0/changelog
so it should be fine to permit it as well, and that's what we are doing.
None
- Tests
- …
=> Add an upper bound on base

.buildkite/pipeline.yml, default.nix, docker/default.nix, package.yaml, release/default.nix, src/Xrefcheck/Config.hs, xrefcheck.nix
Build an executable for Windows. This requires a proper review from Haskell people, as well as some updates to documentation and release process. To build a windows executable, `nix build -f. --argstr platform windows` .
None
- Tests
- Haddock
and
=> Add a windows build

.buildkite/pipeline.yml, nix/sources.json, stack.yaml, xrefcheck.nix
Makes sure that haskell.nix revision used in CI is the same as most of our other projects have, to reduce number of ghc builds
OPS-1023
- Tests
- Haddock
and
=> [OPS-1023] CI: update dependencies, pin hackage and stackage indexes independently

nix/sources.json, nix/sources.nix, package.yaml, src/Xrefcheck/Config.hs, src/Xrefcheck/Util.hs, stack.yaml, stack.yaml.lock, xrefcheck.nix
Use `lts-17.3`.
Resolves #35.
- Tests
- Haddock
and
=> Bump to lts-17

CHANGES.md, package.yaml
I'd like to make a release before merging #57 since #53 has been merged.
- Tests
- Haddock
and
=> Prepare 0.1.3 release

.buildkite/pipeline.yml
It was accidentally removed in 4eca82663a014918ce1e1ec0eec27095d3dc3e93
=> Add curl package to the auto-release CI job

.stylish-haskell.yaml, CHANGES.md, README.md, exec/Main.hs, package.yaml, src-files/def-config.yaml, src/Xrefcheck/CLI.hs, src/Xrefcheck/Config.hs, src/Xrefcheck/Core.hs, src/Xrefcheck/Scan.hs, src/Xrefcheck/Scanners/Markdown.hs, src/Xrefcheck/Util.hs, tests/Test/Xrefcheck/AnchorsSpec.hs, tests/Test/Xrefcheck/ConfigSpec.hs, tests/Test/Xrefcheck/IgnoreAnnotationsSpec.hs, tests/Test/Xrefcheck/IgnoreRegexSpec.hs, tests/configs/github-config.yaml
It turned out that anchors generated from headers have minor differences in GitHub and GitLab, we handle this here.
Resolves #55 
- Tests
- Haddock
and
=> [#55] GitLab support

CHANGES.md, package.yaml
=> Make 0.2 release

.gitignore, README.md
Problem:
I've met problem with one package version. I use cabal to build project and cabal for some reason decided to use old version of this package. With stack everything fine.
So, I think not only me, but other people prefer cabal over stack.
Solution:
Add note to our README.md that in case of cabal usage it's required to run `stack2cabal` first.
Also ignore all cabal staff so it can't be accidentally added to repo.
Resolves #67 
- Tests
- Haddock
of Public …
=> [#67] Add cabal usage note

src/Xrefcheck/CLI.hs, src/Xrefcheck/Config.hs, src/Xrefcheck/Core.hs, src/Xrefcheck/Progress.hs, src/Xrefcheck/Scan.hs, src/Xrefcheck/Scanners/Markdown.hs, src/Xrefcheck/System.hs, src/Xrefcheck/Util.hs, src/Xrefcheck/Verify.hs, tests/Test/Xrefcheck/AnchorsSpec.hs, tests/Test/Xrefcheck/ConfigSpec.hs, tests/Test/Xrefcheck/IgnoreAnnotationsSpec.hs, tests/Test/Xrefcheck/IgnoreRegexSpec.hs, tests/Test/Xrefcheck/LocalSpec.hs
Problem:
Our style guide requires two spaces indention, but in some places we have four or even more spaces.
Solution:
Delete spaces where it contradicts our style guide.
None
- Tests
- Haddock
and
=> Fix indentions

nix/sources.json
Update dependencies used by CI, to keep them up to date.
https://issues.serokell.io/issue/OPS-1269
- Tests
- Haddock
and
=> CI: bump dependencies

.stylish-haskell.yaml, exec/Main.hs, links-tests/Main.hs, links-tests/Test/Xrefcheck/FtpLinks.hs, package.yaml, src/Xrefcheck/CLI.hs, src/Xrefcheck/Command.hs, src/Xrefcheck/Config.hs, src/Xrefcheck/Core.hs, src/Xrefcheck/Orphans.hs, src/Xrefcheck/Progress.hs, src/Xrefcheck/Scan.hs, src/Xrefcheck/Scanners/Markdown.hs, src/Xrefcheck/System.hs, src/Xrefcheck/Util.hs, src/Xrefcheck/Verify.hs, tests/Main.hs, tests/Test/Xrefcheck/AnchorsInHeadersSpec.hs, tests/Test/Xrefcheck/AnchorsSpec.hs, tests/Test/Xrefcheck/ConfigSpec.hs, tests/Test/Xrefcheck/IgnoreAnnotationsSpec.hs, tests/Test/Xrefcheck/IgnoreRegexSpec.hs, tests/Test/Xrefcheck/LocalSpec.hs, tests/Test/Xrefcheck/TrailingSlashSpec.hs, tests/Test/Xrefcheck/Util.hs, tests/markdowns/with-annotations/ignore_link.md
Add `deriving`-s have explicit strategies, old implicit `deriving` is a warning.
#96 
- Tests
- Haddock
and
=> Kirill.andreev/deriving strats by def

CHANGES.md, package.yaml
This PR undoes the erroneous version increment.
None, https://github.com/serokell/xrefcheck/pull/68#issuecomment-938538627
- Tests
- Haddock
and
=> Undo errorneous version increment

src-files/def-config.yaml, src/Xrefcheck/CLI.hs, src/Xrefcheck/Config.hs, src/Xrefcheck/Verify.hs, tests/configs/github-config.yaml, tests/golden/check-localhost/config-check-disabled.yaml, tests/golden/check-localhost/config-check-enabled.yaml
I added new field to VerifyConfig, updated all configuration files in tests, added new CLI option to override config, if it's necessary.
- Fixed #104
=> [#104] Add maxRetries to configurable options

.github/pull_request_template.md, CHANGES.md
Some changelog entries were missing from recent PRs. This PR adds those missing entries.
Fixed none
- Tests
- Haddock
and
=> [Chore] Add missing changelog entries

src/Xrefcheck/CLI.hs
Problem: The help message of the `--mode` option doesn't say which modes
are supported. The only way for a user to find that out is to
purposefully call `--mode` with a garbage value, and then xrefcheck will
complain about it and print the list of supported modes.
Solution: Improve the help message to display the list of supported
modes.
It now looks like this:
```
-m,--mode KEYWORD        local-only: Verify only references to local files.
external-only: Verify only external references (e.g. http or ftp URLs).
full: Verify all references.
Default mode: full.
```
Fixes #121
- Tests …
=> [#121] Improve help message of `--mode` command line option

CHANGES.md, src/Xrefcheck/Scan.hs, tests/Test/Xrefcheck/TrailingSlashSpec.hs, tests/golden/check-cli/check-cli.bats
This adds some bytes to forbid verifying a single file.
Resolves #90 
- Tests
- Haddock
and
=> [#90] Forbid verifying a single file

.reuse/dep5, CHANGES.md, src/Xrefcheck/Verify.hs, tests/golden/check-anchors/check-anchors.bats, tests/golden/check-anchors/check-relative-anchor.md, tests/golden/check-anchors/expected.gold, tests/golden/check-anchors/no-anchor.md, tests/golden/check-cli/expected.gold.license, tests/golden/check-localhost/expected.gold.license
Fix bug with ignoring checks for relative anchors by normalizing those links before check.
Fixes #120
- Tests
- Haddock
and
=> [#120] Fix bug with ignoring checks for relative anchors

.github/pull_request_template.md, CHANGES.md
The pull request template has a few broken links in it - this PR fixes those links.
While we're here, I also added a checklist for release-specific activities, like we recently did in universum, and removed the `0.2.1` section from the changelog, since the 0.2.1 release hasn't actually been made yet.
None
- Tests
- Haddock
and
=> [Chore] Fix PR template

.github/pull_request_template.md, CHANGES.md, package.yaml
v0.2.1 release
None
with a summary of all user-facing changes.
*  I made sure a tag was created using the format `vX.Y.Z`
=> v0.2.1 release

Makefile, make/Makefile
Problem: Most of our projects have a makefile for running common tasks. We should add one to xrefcheck as well.
Solution: Add makefile.
Fixes #134 
- Tests
- Haddock
and
=> [#134] Add makefile

CHANGES.md, src/Xrefcheck/Command.hs, src/Xrefcheck/Config.hs, src/Xrefcheck/Scanners/Markdown.hs, tests/Test/Xrefcheck/Util.hs, tests/golden/check-cli/config-no-scan-ignored.yaml, tests/golden/check-ignoreRefs/config-check-disabled.yaml, tests/golden/check-ignoreRefs/config-check-enabled.yaml, tests/golden/check-ignored/config-ignored.yaml, tests/golden/check-notScanned/config-directory.yaml, tests/golden/check-notScanned/config-full-path.yaml, tests/golden/check-notScanned/config-nested-directories.yaml, tests/golden/check-notScanned/config-wildcard.yaml, tests/golden/check-virtualFiles/config-virtualFiles.yaml
Problem: As of #159 we made all config fields optional. However, it makes sense to make the `flavor` field mandatory, as it affects correctness and the user must make a choice here.
Solution: Make `flavor` a required parameter.
Fixes #180 
- Tests
- Haddock
and …
=> [#180] Make `flavor` a required parameter

package.yaml, src/Xrefcheck/Core.hs, stack.yaml, stack.yaml.lock
Problem: We depend on `roman-numerals` package,
which is outdatead and can't be built with
GHC 9.2.4, which is used by Hackage to generate Haddocks.
Solution: the only place we use this package is showing header levels, so we can show them "by hands" instead
Fixes #179 
- Tests
- Haddock
and
=> [#179] Drop `roman-numerals`

CHANGES.md, src/Xrefcheck/Core.hs, src/Xrefcheck/Verify.hs
Problem: as in #166, we use are wrongly calling links to current file e.g. `[a](#heading)` as "local", which is confusing with using "local" as "link to anything in current repository".
Solution: call them "links to current file"
and rename constructor `LocalLoc` to `CurrentFileLoc`
Fixes #166
- Tests
- Haddock
and
=> [#166] Rename references to current file

nix/sources.json, package.yaml, stack.yaml, stack.yaml.lock
In #158, we started using `optFootnotes` from the `cmark-gfm` package.
This feature hadn't yet been released on hackage, so we pulled the package from its github repo.
Since then, cmark-gfm-0.2.5 has been released on hackage.
We can now use it in xrefcheck. To do that, we need to update haskell.nix/hackage.nix and nixpkgs.
None
- Tests
- Haddock
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c …
=> [Chore] Bump nix dependencies

CHANGES.md, src/Xrefcheck/Scanners/Markdown.hs, tests/golden/check-images/check-images.bats, tests/golden/check-images/check-images.md, tests/golden/check-images/expected.gold
Problem: We should add support for image links.
Solution: Extract image links as regular links.
Fixes #92 
- Tests
- Haddock
and
* Change the tag and title using the format `vX.Y.Z`.
* Write a summary of all user-facing changes.
* Deselect the "This is a …
=> [#92] Add support for image links

CHANGES.md
Accidently I've not placed correctly changelog entry for #199, so now we need to fix this
=> fixup CHANGES.md

.buildkite/pipeline.yml, .xrefcheck.yaml
Problem: Currently, there are some invalid links in the repository, mostly for tests, so one has to add some CLI options for `xrefcheck` to succeed.
Solution: Added a new minimal `.xrefcheck.yaml` config file such that `xrefcheck` succeeded without any options.
Fixes #227
- Tests
- Haddock
and
under the "Unreleased" section to a new …
=> [#227] Add .xrefcheck.yaml config to repo

.github/workflows/danger.yml, LICENSES/LicenseRef-MIT-OA.txt, danger/branch-name.rb, danger/commit-style.rb, danger/helpers.rb, danger/instant-checks.rb, danger/licenses.rb, danger/premerge-checks.rb, danger/trailing-whitespaces.rb
Problem: it would be helpful to have checks for common rules on styling commits and stuff, to avoid checking those manually every time.
Solution: add Danger checks, mostly the same we had in Morley.
None
- Tests
- Haddock
and
* Change the tag and title using the …
=> [Chore] Add danger checks

README.md
Problem: we'd like to get some statistics about our users. There is a tool called [Scarf](https://about.scarf.sh/) that can be used for this purpose.
Solution:
1. Create a Docker package in Scarf which acts as a proxy, so that instead of `docker pull serokell/xrefcheck` one will use `docker pull serokell.docker.scarf.sh/serokell/xrefcheck` and Scarf will automatically record some (anonymyzed) data.
2. Create a File package in Scarf which acts as another proxy.    It downloads artifacts from GitHub releases, e. g.: https://serokell.gateway.scarf.sh/xrefcheck/v0.2.2/xrefcheck-x86_64-linux
3. Mention these links in usage instructions.
4. Add a tracking pixel to README to also get statistics about README views.
None
If something in this list is …
=> [Chore] Incorporate Scarf

.github/workflows/ci.yml
Problem: Currently CI checks aren't run on the default branch.
Solution: Run CI pipeline with checks on 'master' too.
Fixes #
- Tests
- Haddock
and
* Change the tag and title using the format `vX.Y.Z`.
* Write a summary of all user-facing changes.
* Deselect the …
=> [Chore] Run CI on default branch
